#!/usr/bin/perl


my $pid = fork();
if ($pid < 0) {
    die "fork: $!";
} elsif ($pid) {
  exit 0;
}



use Redis;
use Redis::List;

$BASE = "/var/sites/turknettlabs.com/public";

$FULL_DIR = "$BASE/full_images";
$UPLOAD_DIR = "$BASE/griddle_images";
$MIDSIZE_DIR = "$BASE/mid_images";
$THUMB_DIR = "$BASE/thumb_images";



my $redis = Redis->new(server => 'grd-mysql-01.griddle.com:6379');

open(L, ">> /tmp/convert.log");

while(1) {

  $filename = $redis->lpop("img.process");

  $now = `/bin/date`;
  chop $now;

  if($filename) {
    print L "$now - $filename\n";
    system("/usr/bin/convert -auto-orient -strip -resize 290x290 -quality 60 '$FULL_DIR/$filename' '$UPLOAD_DIR/$filename'");
    system("/usr/bin/convert -auto-orient -strip -resize 640x640 -quality 60 '$FULL_DIR/$filename' '$MIDSIZE_DIR/$filename'");
    system("/usr/bin/convert -auto-orient -strip -resize 75x75 -quality 60 '$FULL_DIR/$filename' '$THUMB_DIR/$filename'");
    system("/usr/bin/convert -auto-orient -strip -quality 60 '$FULL_DIR/$filename' '$FULL_DIR/$filename'");
  }

  sleep(1);
}


