#!/usr/bin/perl

use DBI;

$dbh = DBI->connect("DBI:mysql:database=griddleng:www.griddle.com", "root", "8dogson42fence");

$sth = $dbh->prepare("SELECT uid, gid FROM posts");

$sth->execute;

while(($uid, $gid) = $sth->fetchrow_array) {
    if(!$SEEN{"u$uid-g$gid"}) {
       $COUNTS{$gid}++;
       $SEEN{"u$uid-g$gid"} = 1;
    }
}
$sth->finish;

foreach $gid (keys %COUNTS) {
   
   $sth = $dbh->prepare("UPDATE griddles SET involved=$COUNTS{$gid} WHERE gid=$gid");
   $sth->execute;

}



$dbh->disconnect;

